[pytest]
testpaths = steps
addopts = -v --alluredir=allure-results --html=reports/pytest-report.html --self-contained-html
markers =
    playwright: escenarios de Playwright
    carrito: escenarios del carrito
    compra: escenarios de proceso de compra
    dos_productos: escenarios con dos productos
